services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  postgres:
    image: postgres:18.4-bookworm
    environment:
      POSTGRES_DB: cloudcost
      POSTGRES_USER: cloudcost
      POSTGRES_PASSWORD: cloudcost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U cloudcost -d cloudcost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s

volumes:
  postgres_data:
